/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      // Stitch "Academic Editorial" color tokens (see uploaded design
      // export). Ported as-is so future pages can reference them by name
      // (e.g. bg-surface, text-on-surface-variant, border-outline-variant).
      colors: {
        "on-surface": "#1a1c1a",
        "on-primary-fixed-variant": "#23501e",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#c7c6c6",
        background: "#faf9f6",
        "on-primary-container": "#9dd090",
        "on-tertiary-fixed-variant": "#504536",
        outline: "#72796e",
        "on-error": "#ffffff",
        "tertiary-container": "#5a4e3f",
        "surface-container-low": "#f4f3f1",
        surface: "#faf9f6",
        "surface-container-highest": "#e3e2e0",
        "on-secondary-container": "#636262",
        error: "#ba1a1a",
        "on-primary-fixed": "#002201",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#464747",
        "surface-container-high": "#e9e8e5",
        "surface-container": "#efeeeb",
        "surface-variant": "#e3e2e0",
        "on-surface-variant": "#42493e",
        "on-secondary-fixed": "#1b1c1c",
        "on-error-container": "#93000a",
        "secondary-fixed": "#e4e2e2",
        "secondary-container": "#e1dfdf",
        "error-container": "#ffdad6",
        "on-background": "#1a1c1a",
        tertiary: "#423729",
        "outline-variant": "#c2c9bb",
        "tertiary-fixed": "#f1e0cc",
        "primary-container": "#2d5a27",
        "inverse-primary": "#a1d494",
        "on-secondary": "#ffffff",
        secondary: "#5e5e5e",
        "on-tertiary-fixed": "#231a0e",
        "on-tertiary-container": "#d0c0ad",
        "inverse-on-surface": "#f2f1ee",
        "primary-fixed": "#bcf0ae",
        "surface-tint": "#3b6934",
        "on-primary": "#ffffff",
        "inverse-surface": "#2f312f",
        primary: "#154212",
        "primary-fixed-dim": "#a1d494",
        "surface-bright": "#faf9f6",
        "surface-dim": "#dbdad7",
        "tertiary-fixed-dim": "#d5c4b1",
      },
      // NOTE: deliberately NOT overriding the built-in `full` key (Stitch's
      // export sets it to 0.75rem instead of a true pill). Profile.jsx
      // relies on the stock `rounded-full` (9999px) for a circular avatar,
      // and that page is out of scope this phase — remapping `full` here
      // would silently turn that circle into a rounded square. Wherever
      // the Stitch design wants that ~8-12px "capsule" radius (badges,
      // chips), use `rounded-xl` below instead, which now equals 8px.
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
      },
      spacing: {
        "container-max": "1280px",
        "section-gap": "80px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        unit: "4px",
        gutter: "24px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        metadata: ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        metadata: ["13px", { lineHeight: "18px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
